# action.yml
name: Python test
on:
  push:
    branches: [ ci-cd ]
jobs:
  gpu_checks:
    name: GPU Tests
    runs-on: self-hosted
    strategy:
      matrix:
        Cuda: ["10.1", "10.2", "11.0"]
    steps:
    - uses: actions/checkout@v2
      with:
        cuda-version: ${{ matrix.Cuda }}
    - name: Run GPU tests ${{ matrix.cuda-version }}
      run: |
        cd .github/workflows
        CUDA_HOME="/usr/local/cuda-${{ matrix.cuda-version }}/" PATH="/usr/local/cuda-${{ matrix.cuda-version }}/bin":$PATH make docker-test-run-zsh
#    - name: Install package
#      run: |
#        echo "TORCH_LIB=/usr/lib64/python3.6/site-packages/torch/lib:$TORCH_LIB" >> $GITHUB_ENV
#        docker run -i --gpus device=all --name rat_manylinux -v $(pwd):/rational_activations df31f4268b9b zsh
#        python setup.py install
#        python -m pytest
# run: |
#        echo "CUDA_HOME=/usr/local/cuda-10.2/" >> $GITHUB_ENV
#        echo "PATH=/usr/local/cuda-10.2/bin:$PATH" >> $GITHUB_ENV
#        make docker-test-run-zsh
#steps:
  #    - uses: actions/checkout@v2
  #    - name: Build test image
  #      run: |
  #        make docker-test-image
  #    - name: Run GPU tests
  #      run: |
  #        make docker-test-run