# action.yml
name: Python test
on:
  push:
    branches: [ ci-cd ]
jobs:
  gpu_checks:
    name: Tests (Cuda, Python) =
    runs-on: self-hosted
    strategy:
      matrix:
        cuda-version: ['10.1']
        python-version: ['3.7']
    steps:
    - uses: actions/checkout@v2
      with:
        cuda-version: ${{ matrix.cuda-version }}
        python-version: ${{ matrix.python-version }}
    - name: Run GPU tests CUDA=${{ matrix.cuda-version }} & Python${{ matrix.python-version }}
      uses: ml-research/rational_activations@v1
      with:
        python-version: ${{ matrix.python-version }}
        cuda-version: ${{ matrix.cuda-version }}

# run: |
#        echo "CUDA_HOME=/usr/local/cuda-10.2/" >> $GITHUB_ENV
#        echo "PATH=/usr/local/cuda-10.2/bin:$PATH" >> $GITHUB_ENV